# PostgreSQL (prod)
spring.datasource.url=jdbc:postgresql://localhost:5432/presenciadb
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.h2.console.enabled=false

app.jwt.secret=${JWT_SECRET}

spring.thymeleaf.cache=true
